#!/bin/env bash

folders=$(find src/content -mindepth 1 -maxdepth 1 -type d | sort --human-numeric-sort --reverse)
json="["
first=true
counter=0
for folder in $folders; do
    name=$(basename "$folder")
    if [[ ${#name} -ge 4 && $name =~ ^[0-9]{4} ]]; then
        year=${name:0:4}
        title=${name:5}
        id="id$counter"
        poster_image=""

        mapfile -t images < <(find "$folder" -maxdepth 1 -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.gif' -o -iname '*.webp' \) | sort --random-sort)
        if [ ${#images[@]} -gt 0 ]; then
            for i in "${!images[@]}"; do
                images[$i]="./$(basename $(dirname "${images[$i]}"))/$(basename "${images[$i]}")"
                # images[$i]=$(pwd)/"${images[$i]}"
            done
            # poster_image="./$(basename $(dirname "${images[0]}"))/$(basename "${images[0]}")"
            poster_image="${images[0]}"
            images=$(printf '"%s", ' "${images[@]}")
            images="${images%, }" # Remove trailing comma and space
        fi

        if [ "$first" = true ]; then
            first=false
        else
            json="$json,"
        fi

        json="$json$(printf '{
    "id": "%s",
    "title": "%s",
    "year": %d,
    "images": [%s],
    "posterImage": "%s",
    "description": "",
    "materials": [],
    "pubDate": "%s",
    "updatedDate": "%s"
}' "$id" "$title" "$year" "$images" "$poster_image" "$(date --iso-8601)" "$(date --iso-8601)")"

        counter=$((counter + 1))
        # read -ar images < <(printf '%s,\n' "${images[@]}"| jq -R . | jq -s .)
        # json="$json{\"year\":\"$year\",\"title\":\"$title\",\"poster-image\":\"$poster_image\",\"images\":[$images]}"
    fi
done
json="$json]"
echo "$json" > src/content/projects.json